#ifndef TX_USER_H
#define TX_USER_H

#define TX_MAX_PRIORITIES                       32
#define TX_MINIMUM_STACK                        512
#define TX_TIMER_TICKS_PER_SECOND               (1000UL)
#define TX_REACTIVATE_INLINE
#define TX_DISABLE_STACK_FILLING
#define TX_DISABLE_PREEMPTION_THRESHOLD
#define TX_DISABLE_REDUNDANT_CLEARING
#define TX_DISABLE_NOTIFY_CALLBACKS
#define TX_INLINE_THREAD_RESUME_SUSPEND
#define TX_NOT_INTERRUPTABLE

#endif
